### ISSUE TITLE
clarify BCE release roadmap

### ISSUE THREAD

**Issue by aculich** [berkeley-stat/bce-documentation#8]
We should publish a clearer release roadmap as Ronald Sprouse suggests on bce@lists:

> The download page has a 'Release schedule' section that says the plan
> is for two releases per year, spring and fall, and yet the current
> release is named 'summer'. Can you clarify the expected release
> schedule? Is it always at least spring and fall, with the possibility
> of a summer release? I'm assuming winter releases aren't anticipated
> since there is no winter academic term.

**Comment by aculich** [comment]
Indeed, I think we're collectively experimenting to find the right release process-- a balance between:
- stability for use in teaching (including across multiple semesters)
- recent enough to make use of more current software packages
- security updates and Ubuntu's release end of life: http://www.ubuntu.com/info/release-end-of-life

![Ubuntu LTS release cycle showing release end of life visually](http://assets.ubuntu.com/sites/ubuntu/1498/u/img/graphs/image-release-cycle-large.png)

**Comment by ryanlovett** [comment]
Fixed in 591ba20.
